# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ library_update ]

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - run: npm ci
    - run: npm run build
    - name: Fetch library stats
      uses: dawidd6/action-download-artifact@v2
      with:
        name: ${{ secrets.LIBRARY_ACCESS_TOKEN }}
        workflow: build-site.yml
        workflow_conclusion: success
        branch: master
        name: artifact_name
        path: _data
        repo: kingsquill/william-perkins
    - name: Publish site
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: _site
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [site]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: site # The folder the action should deploy.
